version: '3'

services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresSolutions_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  users:
#    build: ./
#    restart: always
#    container_name: clearSolutions
#    ports:
#      - "9090:9090"
#    depends_on:
#      - postgres

volumes:
  postgresSolutions_data: {}