version: '3'

services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresSolutions_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis-data:/data


        #  users:
#    build: ./
#    restart: always
#    container_name: clearSolutions
#    ports:
#      - "9090:9090"
#    depends_on:
#      - postgres

volumes:
  postgresSolutions_data: {}
  redis_data : {}