spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    cache-names:
      -cacheUser
    redis:
      time-to-live: 10000
  redis:
    host: localhost
    port: 6379

  sql:
    init:
      mode: always

server:
  port: 9090

user:
  minAge: 18